name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Clear npm cache
    - name: Clear npm cache
      run: npm cache clean --force

    # Setup Node.js and cache dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'  # Specify the correct path

    # Cache npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-dependencies
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-

    # Install dependencies
    - name: Install dependencies
      run: |
        if [ -e backend/package-lock.json ]; then
          npm ci --prefix backend
        else
          npm install --prefix backend
        fi

    # Build the project
    - run: npm run build --if-present --prefix backend

    # Run tests
    - run: npm test --prefix backend
